"""Test script to verify experiment framework functionality.
    Generated by Claude Haiku 4.5 on 25-05-2026."""

import sys
import traceback
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))


def test_imports():
    """Test that all modules can be imported."""
    print("\n" + "="*60)
    print("TEST 1: Imports")
    print("="*60)
    
    try:
        from trajectory import TrajectoryRecord
        print("✓ trajectory.TrajectoryRecord")
    except Exception as e:
        print(f"✗ trajectory.TrajectoryRecord: {e}")
        traceback.print_exc()
        return False
    
    try:
        from experiment_config import ExperimentConfig, get_config, EXPERIMENT_CONFIGS
        print("✓ experiment_config")
    except Exception as e:
        print(f"✗ experiment_config: {e}")
        traceback.print_exc()
        return False
    
    try:
        from base_experiment import BaseExperiment
        print("✓ base_experiment.BaseExperiment")
    except Exception as e:
        print(f"✗ base_experiment.BaseExperiment: {e}")
        traceback.print_exc()
        return False
    
    try:
        from smw_experiment import SMWExperiment
        print("✓ smw_experiment.SMWExperiment")
    except Exception as e:
        print(f"✗ smw_experiment.SMWExperiment: {e}")
        traceback.print_exc()
        return False
    
    try:
        from rl_experiment import RLExperiment
        print("✓ rl_experiment.RLExperiment")
    except Exception as e:
        print(f"✗ rl_experiment.RLExperiment: {e}")
        traceback.print_exc()
        return False
    
    try:
        from experiment_runner import ExperimentRunner, run_single_experiment
        print("✓ experiment_runner.ExperimentRunner")
    except Exception as e:
        print(f"✗ experiment_runner.ExperimentRunner: {e}")
        traceback.print_exc()
        return False
    
    print("\n✓ All imports successful!")
    return True


def test_trajectory_record():
    """Test TrajectoryRecord creation and conversion."""
    print("\n" + "="*60)
    print("TEST 2: TrajectoryRecord")
    print("="*60)
    
    try:
        from trajectory import TrajectoryRecord
        
        record = TrajectoryRecord(
            sequence="ACGTACGT",
            oracle_score=0.75,
            surrogate_score=0.72,
            method="smw",
            iteration=0,
            run_id=1,
            seed=42,
            min_hamming_distance=5,
            dataset="tfbind8",
            transcription_factor="SIX6_REF_R1",
        )
        
        print(f"✓ Created TrajectoryRecord: {record}")
        
        # Test to_dict conversion
        record_dict = record.to_dict()
        print(f"✓ to_dict() conversion: {len(record_dict)} fields")
        
        expected_keys = {
            'method', 'run_id', 'seed', 'iteration', 'sequence',
            'oracle_score', 'surrogate_score', 'min_hamming_distance',
            'dataset', 'transcription_factor'
        }
        
        if set(record_dict.keys()) == expected_keys:
            print(f"✓ All expected keys present")
        else:
            missing = expected_keys - set(record_dict.keys())
            extra = set(record_dict.keys()) - expected_keys
            if missing:
                print(f"✗ Missing keys: {missing}")
            if extra:
                print(f"✗ Extra keys: {extra}")
            return False
        
        print("\n✓ TrajectoryRecord tests passed!")
        return True
        
    except Exception as e:
        print(f"✗ TrajectoryRecord test failed: {e}")
        traceback.print_exc()
        return False


def test_config():
    """Test configuration loading."""
    print("\n" + "="*60)
    print("TEST 3: Configuration")
    print("="*60)
    
    try:
        from experiment_config import get_config, EXPERIMENT_CONFIGS
        
        # Test all keywords
        keywords = list(EXPERIMENT_CONFIGS.keys())
        print(f"Available keywords: {keywords}")
        
        for keyword in keywords:
            config = get_config(keyword)
            method = config.method
            dataset = config.dataset
            
            # Get num_iterations
            if method == "smw":
                num_iters = config.smw_config.num_iterations
            else:
                num_iters = config.rl_config.num_iterations
            
            print(f"✓ {keyword:20s} - {method:3s} on {dataset:10s} ({num_iters} iterations)")
        
        # Test invalid keyword
        try:
            get_config("invalid_keyword")
            print("✗ Should raise error for invalid keyword")
            return False
        except ValueError as e:
            print(f"✓ Correctly raised error for invalid keyword: {e}")
        
        print("\n✓ Configuration tests passed!")
        return True
        
    except Exception as e:
        print(f"✗ Configuration test failed: {e}")
        traceback.print_exc()
        return False


def test_smw_setup():
    """Test SMW experiment setup."""
    print("\n" + "="*60)
    print("TEST 4: SMW Experiment Setup")
    print("="*60)
    
    try:
        from experiment_config import get_config
        from smw_experiment import SMWExperiment
        
        # Test TFBind8
        print("\nTesting SMW on TFBind8...")
        config = get_config("smw_tfbind8")
        experiment = SMWExperiment(config, run_id=1)
        
        print(f"  Config method: {config.method}")
        print(f"  Config dataset: {config.dataset}")
        print(f"  Run ID: {experiment.run_id}")
        print(f"  Seed: {experiment.seed}")
        
        # Setup
        print("  Running setup()...")
        experiment.setup()
        
        # Check that required attributes are set
        assert experiment.oracle is not None, "Oracle not initialized"
        assert experiment.surrogate is not None, "Surrogate not initialized"
        assert experiment.train_df is not None, "train_df not initialized"
        assert experiment.walker is not None, "Walker not initialized"
        assert experiment.token_to_idx is not None, "token_to_idx not initialized"
        assert experiment.X_train_encoded is not None, "X_train_encoded not initialized"
        
        print(f"  ✓ Oracle initialized")
        print(f"  ✓ Surrogate initialized")
        print(f"  ✓ Walker initialized")
        print(f"  ✓ Training data loaded: {len(experiment.train_df)} sequences")
        print(f"  ✓ Sequence length: {len(experiment.train_df['sequence'].iloc[0])}")
        
        # Test GB1
        print("\nTesting SMW on GB1...")
        config_gb1 = get_config("smw_gb1")
        experiment_gb1 = SMWExperiment(config_gb1, run_id=1)
        experiment_gb1.setup()
        
        assert experiment_gb1.oracle is not None, "GB1 Oracle not initialized"
        print(f"  ✓ GB1 setup successful")
        
        print("\n✓ SMW setup tests passed!")
        return True
        
    except Exception as e:
        print(f"✗ SMW setup test failed: {e}")
        traceback.print_exc()
        return False


def test_rl_setup():
    """Test RL experiment setup."""
    print("\n" + "="*60)
    print("TEST 5: RL Experiment Setup")
    print("="*60)
    
    try:
        from experiment_config import get_config
        from rl_experiment import RLExperiment
        
        # Test TFBind8
        print("\nTesting RL on TFBind8...")
        config = get_config("rl_tfbind8")
        experiment = RLExperiment(config, run_id=1)
        
        print(f"  Config method: {config.method}")
        print(f"  Config dataset: {config.dataset}")
        print(f"  Run ID: {experiment.run_id}")
        print(f"  Seed: {experiment.seed}")
        
        # Setup (this may take a while due to LSTM pretraining)
        print("  Running setup() - this may take a few seconds...")
        experiment.setup()
        
        # Check that required attributes are set
        assert experiment.oracle is not None, "Oracle not initialized"
        assert experiment.surrogate is not None, "Surrogate not initialized"
        assert experiment.train_df is not None, "train_df not initialized"
        assert experiment.lstm_model is not None, "LSTM model not initialized"
        assert experiment.token_to_idx is not None, "token_to_idx not initialized"
        
        print(f"  ✓ Oracle initialized")
        print(f"  ✓ Surrogate (RF) initialized")
        print(f"  ✓ LSTM model pretrained")
        print(f"  ✓ Training data loaded: {len(experiment.train_df)} sequences")
        
        print("\n✓ RL setup tests passed!")
        return True
        
    except Exception as e:
        print(f"✗ RL setup test failed: {e}")
        traceback.print_exc()
        return False


def test_smw_single_iteration():
    """Test SMW single iteration."""
    print("\n" + "="*60)
    print("TEST 6: SMW Single Iteration")
    print("="*60)
    
    try:
        from experiment_config import get_config
        from smw_experiment import SMWExperiment
        
        config = get_config("smw_tfbind8")
        experiment = SMWExperiment(config, run_id=1)
        experiment.setup()
        
        print(f"Running iteration 0...")
        records = experiment.run_single_iteration(iteration=0)
        
        print(f"✓ Got {len(records)} records")
        
        # Check first record (seed sequence)
        if len(records) > 0:
            rec = records[0]
            print(f"  First record:")
            print(f"    Sequence: {rec.sequence[:20]}... (length {len(rec.sequence)})")
            print(f"    Oracle: {rec.oracle_score:.4f}")
            print(f"    Surrogate: {rec.surrogate_score:.4f}")
            print(f"    Hamming: {rec.min_hamming_distance}")
            print(f"    Iteration: {rec.iteration}")
            
            # Verify all records have required fields
            for i, rec in enumerate(records):
                assert rec.sequence is not None
                assert rec.oracle_score is not None
                assert rec.surrogate_score is not None
                assert rec.min_hamming_distance is not None
                assert rec.iteration is not None
                assert rec.method == "smw"
        
        print(f"\n✓ SMW iteration test passed!")
        return True
        
    except Exception as e:
        print(f"✗ SMW iteration test failed: {e}")
        traceback.print_exc()
        return False


def test_rl_single_iteration():
    """Test RL single iteration."""
    print("\n" + "="*60)
    print("TEST 7: RL Single Iteration")
    print("="*60)
    
    try:
        from experiment_config import get_config
        from rl_experiment import RLExperiment
        
        config = get_config("rl_tfbind8")
        experiment = RLExperiment(config, run_id=1)
        experiment.setup()
        
        print(f"Running iteration 0 (this will take a moment)...")
        records = experiment.run_single_iteration(iteration=0)
        
        print(f"✓ Got {len(records)} records")
        
        # Check first record
        if len(records) > 0:
            rec = records[0]
            print(f"  First record:")
            print(f"    Sequence: {rec.sequence[:20]}... (length {len(rec.sequence)})")
            print(f"    Oracle: {rec.oracle_score:.4f}")
            print(f"    Surrogate: {rec.surrogate_score:.4f}")
            print(f"    Hamming: {rec.min_hamming_distance}")
            print(f"    Iteration: {rec.iteration}")
            
            # Verify all records have required fields
            for i, rec in enumerate(records):
                assert rec.sequence is not None
                assert rec.oracle_score is not None
                assert rec.surrogate_score is not None
                assert rec.min_hamming_distance is not None
                assert rec.iteration is not None
                assert rec.method == "rl"
        
        print(f"\n✓ RL iteration test passed!")
        return True
        
    except Exception as e:
        print(f"✗ RL iteration test failed: {e}")
        traceback.print_exc()
        return False


def test_experiment_runner():
    """Test ExperimentRunner creation and basic functionality."""
    print("\n" + "="*60)
    print("TEST 8: ExperimentRunner")
    print("="*60)
    
    try:
        from experiment_runner import ExperimentRunner
        
        print("Creating ExperimentRunner for smw_tfbind8...")
        runner = ExperimentRunner(keyword="smw_tfbind8", results_dir="results_test")
        
        print(f"✓ Runner created")
        print(f"  Keyword: {runner.keyword}")
        print(f"  Method: {runner.config.method}")
        print(f"  Dataset: {runner.config.dataset}")
        print(f"  Num runs: {runner.config.num_runs}")
        print(f"  Results dir: {runner.results_dir}")
        
        print("\n✓ ExperimentRunner tests passed!")
        return True
        
    except Exception as e:
        print(f"✗ ExperimentRunner test failed: {e}")
        traceback.print_exc()
        return False


def main():
    """Run all tests."""
    print("\n" + "#"*60)
    print("# EXPERIMENT FRAMEWORK TEST SUITE")
    print("#"*60)
    
    tests = [
        ("Imports", test_imports),
        ("TrajectoryRecord", test_trajectory_record),
        ("Configuration", test_config),
        ("SMW Setup", test_smw_setup),
        ("RL Setup", test_rl_setup),
        ("SMW Iteration", test_smw_single_iteration),
        ("RL Iteration", test_rl_single_iteration),
        ("ExperimentRunner", test_experiment_runner),
    ]
    
    results = {}
    
    for name, test_func in tests:
        try:
            results[name] = test_func()
        except Exception as e:
            print(f"\n✗ {name} crashed: {e}")
            traceback.print_exc()
            results[name] = False
    
    # Summary
    print("\n" + "#"*60)
    print("# TEST SUMMARY")
    print("#"*60)
    
    passed = sum(1 for v in results.values() if v)
    total = len(results)
    
    for name, result in results.items():
        status = "✓ PASS" if result else "✗ FAIL"
        print(f"{status:8s} - {name}")
    
    print(f"\n{passed}/{total} tests passed")
    
    if passed == total:
        print("\n🎉 All tests passed! Framework is ready to use.")
        return 0
    else:
        print(f"\n⚠️  {total - passed} test(s) failed. See details above.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
